### ISSUE TITLE
When calling a shuttle train any "Interups" added to the train previously are wiped out

### ISSUE THREAD

**Issue by ShaneYu** [StefanTT/factorio-ShuttleTrain#11]
In Factorio 2.0 you can add "Interrupts" to the trains, I use one in my trains to trigger refuelling and was trying to use it with the shuttle trains. However when you call a train, that train has it's interrupts wiped out.

It would be awesome if we could use "Interrupts" with the shuttle trains so they can still go off an refuel and various other things. As we can just add refuelling at the shuttle train depots, it's not a desperate thing, but would be a nice to have.

**Comment by ShaneYu** [comment]
It's worth noting too that shuttle trains that go to stations with circuit networks often end up with a schedule being pushed onto it.

Wonder if we are able to do one of the following to fix it too:

- Prevent schedules being added to the trains when called to a nearby station
- Add an option to that allows preventing trains being called to the nearest station and instead always uses the player position along the track; so we can disable it when we have smart train stations setup.

**Comment by ShaneYu** [comment]
When I get chance I'll raise a PR to add in a new option to allow preventing of using nearby stations and instead use nearest track entity instead.

As for the original issue regarding the interrupts, I don't know enough about the modding etc to be able to fix that at this time.

**Comment by StefanTT** [comment]
Set the station filter correctly and shuttle trains will refuse to use these stations. Stations that contain any of these strings will not show up in the station list when choosing a destination and shuttle trains will refuse to pick you up there.

E.g. in my current game I have set the "Station names to filter" to: Refuel,↦,↤

**Comment by StefanTT** [comment]
Regarding interrupts: I am not completely convinced if interrupts are a thing to be implemented. When I call a shuttle train I want it to come now and not to do some sort of interrupt first while I wait. Same when I ride it.

**Comment by ShaneYu** [comment]
Ah thanks @StefanTT, I was about to code up the extra option as above but there is no point if I can use filters to achieve this, I can see there is a toggle to invert the filter too, which is perfect.

All of my stations have "dynamic" names that use icons, so they weren't exactly useful for choosing a destination. Using the filtering I can limit it to only go to stations starting "Shuttle - "for argument sake and also using such a filter means calling a train wont use stations; based on what you've said.

I will give it a go this evening. Thank you 👍 

--

FYI the only interrupt I was going to add was one to go refuel when the train is low, all of my trains have this; I don't see any other use for interrupts at this time; therefore just re-fuelling them at their depo(s) will be fine.

**Comment by StefanTT** [comment]
I sometimes filter for "/" when I end the production station names with "/i" for input stations and "/o" for output stations, or even some "/io". Nowadays often the arrows I mentioned before.
