### ISSUE TITLE
Crash when Shuttle arrives to nearest station

### ISSUE THREAD

**Issue by ourpxi** [StefanTT/factorio-ShuttleTrain#12]
![image](https://github.com/user-attachments/assets/66ced4de-ec07-4beb-a34c-3245e4fdf0bc)
I called a train and it goes auto to the nearest station to me, when it arrived it crashed, i tried it 3 more times and the same thing happens

[Log file](https://github.com/user-attachments/files/17760194/factorio-current.log)

**Comment by ourpxi** [comment]
Wait
I just noticed this is an error from another mod nvm

**Comment by ourpxi** [comment]
I'm reporting this to the other mod author but maybe you could check it out too

**Comment by ourpxi** [comment]
Here you got the other mod [modpage](https://mods.factorio.com/mod/RailLogisticsDispatcher/)

**Comment by StefanTT** [comment]
Honestly, why should I bother, it's not my code. I will close this issue. You can link to a closed issue if you need to.

**Comment by ourpxi** [comment]
https://github.com/dvilker/FactorioRailLogisticsDispatcher/issues/32
