### ISSUE TITLE
Improve "Select destination" menu (Scroll)

### ISSUE THREAD

**Issue by ST-DDT** [StefanTT/factorio-ShuttleTrain#8]
I have ~500 train stations per surface, so the list of train stations is very long.
If I scroll down to the correct category of station, then I currently also scroll down the station list beyond the amount of actual stations matching that filter.

<details>
<summary>Image 1</summary>

![grafik](https://github.com/StefanTT/factorio-ShuttleTrain/assets/1579362/c855e7c2-7f8c-4e61-8d1f-e7d91705701e)

</details>

That forces me to scroll back up so that I can actually select the station:

<details>
<summary>Image 2</summary>

![grafik](https://github.com/StefanTT/factorio-ShuttleTrain/assets/1579362/1df0555e-7613-4740-aa8c-bc4fea73bd69)

</details>

It would be nice if either scrolling the categories and station names are indenpent from each other
or if selecting a category would scroll back to the top, so it is easier to pick the station

**Comment by StefanTT** [comment]
Hmm, yes, I see what I mean. Or at least scroll up automatically when a category icon is clicked.

I am not completely sure at the moment but you probably know: is the list filtered to only show stations of the current surface?

**Comment by StefanTT** [comment]
Please have a look at version 1.1.9 if this improves the situation. The station list is now scrolled to the top when a category is clicked.

**Comment by ST-DDT** [comment]
> I am not completely sure at the moment but you probably know: is the list filtered to only show stations of the current surface?

Yes, only the current surface's train stops are listed.

> Please have a look at version 1.1.9 if this improves the situation. The station list is now scrolled to the top when a category is clicked.

Works as expected. Thanks for the quick fix.
