### ISSUE TITLE
"Select destination" category images truncated

### ISSUE THREAD

**Issue by ST-DDT** [StefanTT/factorio-ShuttleTrain#9]
The top and the bottom of the category images are truncated.

![grafik](https://github.com/StefanTT/factorio-ShuttleTrain/assets/1579362/ba9c789d-0789-4e33-9939-4650129ae754)

Its easy to see with raw oil/oil liquids or liquids in general.

Station-Name: ![Station-Name](https://github.com/StefanTT/factorio-ShuttleTrain/assets/1579362/1957c6a8-a1da-41e2-8c00-cd536d6a010e)
Category: ![Category](https://github.com/StefanTT/factorio-ShuttleTrain/assets/1579362/f6778806-4ca0-4442-93e7-8804b0f1a2c9)

![Zoomed in](https://github.com/StefanTT/factorio-ShuttleTrain/assets/1579362/54cb6106-ddaa-49f0-b229-1ab65b35d636)
(left: station name; right: category)

**Comment by StefanTT** [comment]
Fixed in version 1.1.9.

**Comment by ST-DDT** [comment]
Works as expected. Thanks for the quick fix and this nice mod ❤️ .
